[package]
name = "chip8-emu"
version = "0.1.0"
authors = ["fhools"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
rand = "0.8.3"
sdl2 = "*"
